import { ProviderCatalogItem } from './types';

export const PROVIDER_CATALOG: Record<string, ProviderCatalogItem> = {
  gemini: {
    id: 'gemini',
    name: 'Google Gemini',
    description: 'Modelos de frontera de Google con Thinking explícito y ventanas de contexto masivas.',
    descriptionEn: 'Google frontier models with explicit Thinking and massive context windows.',
    requiresApiKey: true,
    defaultModel: 'gemini-2.0-flash-thinking-exp-01-21',
    apiKeyPlaceholder: 'AIzaSy...',
    docUrl: 'https://aistudio.google.com/app/apikey',
    models: [
      {
        id: 'gemini-2.0-flash-thinking-exp-01-21',
        name: 'Gemini 2.0 Flash Thinking',
        category: 'thinking',
        description: 'Cadena de pensamiento explícita paso a paso. Ideal para resolver restricciones multivariables complejas.',
        badge: 'Pensamiento Paso a Paso',
        badgeEn: 'Step-by-Step Thinking',
        recommendedFor: 'Itinerarios complejos y cálculo de trade-offs',
        recommendedForEn: 'Complex itineraries & trade-off analysis',
      },
      {
        id: 'gemini-2.5-pro',
        name: 'Gemini 2.5 Pro',
        category: 'reasoning',
        description: 'El modelo insignia de Google para razonamiento profundo y personalización de viajes.',
        badge: 'Insignia / Flagship',
        badgeEn: 'Flagship / Reasoning',
        recommendedFor: 'Planificación profunda y personalización avanzada',
        recommendedForEn: 'Deep planning & advanced customization',
      },
      {
        id: 'gemini-2.0-pro-exp-02-05',
        name: 'Gemini 2.0 Pro',
        category: 'reasoning',
        description: 'Alta precisión lógica para horarios estrictos y resolución de fechas.',
        badge: 'Lógica Avanzada',
        badgeEn: 'Advanced Logic',
        recommendedFor: 'Fechas fijas y resolución de conflictos',
        recommendedForEn: 'Strict dates & conflict resolution',
      },
      {
        id: 'gemini-2.5-flash',
        name: 'Gemini 2.5 Flash',
        category: 'fast',
        description: 'Velocidad de respuesta ultrarrápida con alta calidad multimodal.',
        badge: 'Rápido y Moderno',
        badgeEn: 'Fast & Modern',
        recommendedFor: 'Respuestas instantáneas y lectura de imágenes',
        recommendedForEn: 'Instant responses & rapid image parsing',
      },
      {
        id: 'gemini-1.5-pro',
        name: 'Gemini 1.5 Pro',
        category: 'reasoning',
        description: 'Modelo maduro y estable para documentos extensos.',
        badge: 'Estable Pro',
        badgeEn: 'Stable Pro',
        recommendedFor: 'Documentos extensos y estabilidad',
        recommendedForEn: 'Long documents & stability',
      },
      {
        id: 'gemini-1.5-flash',
        name: 'Gemini 1.5 Flash',
        category: 'fast',
        description: 'Modelo clásico rápido de bajo consumo de cuota.',
        badge: 'Estable Rápido',
        badgeEn: 'Stable Fast',
        recommendedFor: 'Uso general estándar',
        recommendedForEn: 'General standard use',
      },
    ],
  },
  openai: {
    id: 'openai',
    name: 'OpenAI',
    description: 'Modelos de razonamiento o3-mini y GPT-4o reconocidos mundialmente por su precisión lógica.',
    descriptionEn: 'World-renowned OpenAI reasoning and multimodal models including o3-mini and GPT-4o.',
    requiresApiKey: true,
    defaultModel: 'o3-mini',
    apiKeyPlaceholder: 'sk-proj-...',
    docUrl: 'https://platform.openai.com/api-keys',
    models: [
      {
        id: 'o3-mini',
        name: 'OpenAI o3-mini',
        category: 'thinking',
        description: 'Modelo especializado en razonamiento riguroso y optimización de restricciones matemáticas.',
        badge: 'Razonamiento o3',
        badgeEn: 'o3 Reasoning',
        recommendedFor: 'Optimización de itinerarios y resolución de conflictos',
        recommendedForEn: 'Itinerary optimization & constraint solving',
      },
      {
        id: 'gpt-4o',
        name: 'GPT-4o (Omni)',
        category: 'reasoning',
        description: 'Modelo insignia insignia con alta inteligencia multimodal para lectura de boletos y planificación.',
        badge: 'Insignia Multimodal',
        badgeEn: 'Flagship Multimodal',
        recommendedFor: 'Extracción de documentos y viajes detallados',
        recommendedForEn: 'Document extraction & detailed trips',
      },
      {
        id: 'gpt-4o-mini',
        name: 'GPT-4o Mini',
        category: 'fast',
        description: 'Modelo ultrarrápido y sumamente económico para consultas cotidianas.',
        badge: 'Rápido y Económico',
        badgeEn: 'Fast & Affordable',
        recommendedFor: 'Consultas rápidas What-If',
        recommendedForEn: 'Quick What-If queries',
      },
      {
        id: 'o1',
        name: 'OpenAI o1',
        category: 'thinking',
        description: 'Razonamiento profundo de frontera para problemas de planificación de máxima complejidad.',
        badge: 'Razonamiento Profundo',
        badgeEn: 'Deep Reasoning',
        recommendedFor: 'Planificación de viajes intercontinentales complejos',
        recommendedForEn: 'Complex intercontinental multi-leg trips',
      },
    ],
  },
  anthropic: {
    id: 'anthropic',
    name: 'Anthropic Claude',
    description: 'Claude 3.7 Sonnet con razonamiento híbrido y estricto seguimiento de esquemas estructurados.',
    descriptionEn: 'Claude 3.7 Sonnet with hybrid reasoning and rigorous structured schema adherence.',
    requiresApiKey: true,
    defaultModel: 'claude-3-7-sonnet-20250219',
    apiKeyPlaceholder: 'sk-ant-api...',
    docUrl: 'https://console.anthropic.com/settings/keys',
    models: [
      {
        id: 'claude-3-7-sonnet-20250219',
        name: 'Claude 3.7 Sonnet',
        category: 'thinking',
        description: 'Modelo de vanguardia con capacidad de razonamiento híbrido continuo (instantáneo o reflexivo).',
        badge: 'Razonamiento Híbrido',
        badgeEn: 'Hybrid Reasoning',
        recommendedFor: 'Recomendaciones matizadas y estilo de viaje personalizado',
        recommendedForEn: 'Nuanced travel recommendations & pacing',
      },
      {
        id: 'claude-3-5-sonnet-20241022',
        name: 'Claude 3.5 Sonnet',
        category: 'reasoning',
        description: 'Alta coherencia analítica y seguimiento perfecto de estructuras de datos.',
        badge: 'Alta Precisión',
        badgeEn: 'High Precision',
        recommendedFor: 'Planificación estructurada y cero alucinaciones',
        recommendedForEn: 'Structured planning & zero hallucination',
      },
      {
        id: 'claude-3-5-haiku-20241022',
        name: 'Claude 3.5 Haiku',
        category: 'fast',
        description: 'Velocidad de generación instantánea para chat interactivo.',
        badge: 'Ultrarrápido',
        badgeEn: 'Ultra-Fast',
        recommendedFor: 'Respuestas conversacionales en milisegundos',
        recommendedForEn: 'Millisecond conversational turns',
      },
    ],
  },
  ollama: {
    id: 'ollama',
    name: 'Ollama (Local Privado)',
    description: 'Ejecuta modelos en tu propia máquina (DeepSeek-R1, Llama 3.3) 100% privado y sin enviar datos a la nube.',
    descriptionEn: 'Run private models (DeepSeek-R1, Llama 3.3) locally on your machine with 100% privacy.',
    requiresApiKey: false,
    defaultModel: 'deepseek-r1:latest',
    apiKeyPlaceholder: 'No requiere clave (Servidor local)',
    docUrl: 'https://ollama.com',
    models: [
      {
        id: 'deepseek-r1:latest',
        name: 'DeepSeek-R1 (Local)',
        category: 'thinking',
        description: 'Modelo de razonamiento de código abierto que piensa paso a paso antes de emitir la propuesta.',
        badge: 'Pensamiento Local',
        badgeEn: 'Local Thinking',
        recommendedFor: 'Privacidad absoluta con razonamiento profundo',
        recommendedForEn: 'Full privacy with deep reasoning',
      },
      {
        id: 'llama3.3:70b',
        name: 'Llama 3.3 70B (Local)',
        category: 'reasoning',
        description: 'El modelo libre de Meta más capaz para planificación general y redacción.',
        badge: 'Insignia Open Source',
        badgeEn: 'Open Source Flagship',
        recommendedFor: 'Equipos potentes y planificación completa',
        recommendedForEn: 'High-end local rigs & full planning',
      },
      {
        id: 'llama3.1:8b',
        name: 'Llama 3.1 8B (Ligero)',
        category: 'fast',
        description: 'Modelo liviano y ágil que se ejecuta cómodamente en cualquier laptop con 8GB-16GB de RAM.',
        badge: 'Ligero y Rápido',
        badgeEn: 'Lightweight & Fast',
        recommendedFor: 'Cualquier laptop o equipo estándar',
        recommendedForEn: 'Standard laptops & quick turnaround',
      },
      {
        id: 'mistral-small:latest',
        name: 'Mistral Small (Local)',
        category: 'fast',
        description: 'Excelente para comprensión de texto en español e inglés con bajo consumo de memoria.',
        badge: 'Eficiente',
        badgeEn: 'Efficient',
        recommendedFor: 'Uso eficiente de CPU/GPU',
        recommendedForEn: 'Efficient CPU/GPU utilization',
      },
    ],
  },
};
